name: HearthstoneJSON
description: JSON files for Hearthstone
logo: images/logo.png

url: https://hearthstonejson.com

markdown: kramdown

redcarpet:
  # Use Github Flavored Markdown (including triple backticks)
  input: GFM

sass:
  style: :compressed

gems:
  - jekyll-sitemap

exclude:
  - LICENSE
