name: HearthstoneJSON
description: JSON files for Hearthstone
logo: images/logo.png

url: http://hearthstonejson.com
baseurl: "/hearthstonejson"

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

sass:
  style: :compressed

gems:
  - jekyll-sitemap
